[package]
name = "koto-ls"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
koto = { git = "https://github.com/koto-lang/koto" }
parking_lot = "0.12.2"
tokio = { version = "1.37.0", features = ["full"] }
tower-lsp = "0.20.0"
tracing-subscriber = "0.3.18"

[patch."https://github.com/koto-lang/koto"]
koto = { path = "../koto/crates/koto" }
